ProductDeliveryManagement/ProductDeliveryManagement/Controllers/DeliveryPersonsController.cs
using ProductDeliveryManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductDeliveryManagement.Controllers
{
    [Authorize]
    public class DeliveryPersonsController : Controller
    {
        DeliveryManagementDbContext db = new DeliveryManagementDbContext();
        // GET: DeliveryPersons
        public ActionResult Index(int page = 1)
        {
            int totalPages = (int)Math.Ceiling((double)db.DeliveryPeople.Count() / 5);
            ViewBag.TotalPages = totalPages;
            ViewBag.Current = page;
            var data = db.DeliveryPeople.OrderBy(x => x.DeliveryPersonId).Skip((page - 1) * 5).Take(5).ToList();
            return View(data);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(DeliveryPerson person)
        {
            if (ModelState.IsValid)
            {
                db.DeliveryPeople.Add(person);
                db.SaveChanges();
                return Json(new { success = true, message = "Data saved successfully" });
            }
            return Json(new { success = false, message = "Failed to save data" });
        }
        public ActionResult Edit(int id)
        {
            var data = db.DeliveryPeople.FirstOrDefault(d => d.DeliveryPersonId == id);
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(DeliveryPerson person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, data = person });
            }
            return View(person);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var data = new DeliveryPerson { DeliveryPersonId = id };
            db.Entry(data).State = System.Data.Entity.EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ProductDeliveryManagement/ProductDeliveryManagement/Views/DeliveryPersons/Create.cshtml
@model ProductDeliveryManagement.Models.DeliveryPerson
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        <h3>Create new Delivery Person</h3>
        <div class="alert alert-warning alert-dismissible fade show" role="alert" id="alert" style="display:none">
            <strong id="result">Success!</strong> <span id="msg"></span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        @using (Html.BeginForm("Create", "DeliveryPersons", FormMethod.Post, new { id = "frm" }))
        {
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Name, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Phone, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Phone, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Address, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row mb-1">
                <div class="col-4 offset-2">
                    <button type="button" id="save" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
    <div class="col-12">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        $(() => {
            $("#save").click(() => {
                let isValid = $("#frm").valid();
                if (isValid) {
                    let data = $("#frm").serialize();
                    $.ajax({
                        type: "POST",
                        url: "/DeliveryPersons/Create",
                        data: data,
                        dataType: "json",
                        success: (r) => {
                            $("#msg").html(r.message);
                            $("#alert").removeClass("alert-warning")
                                .addClass("alert-success")
                                .show();
                            $("#frm").trigger('reset');
                        }
                    });
                }
            });
        });
    </script>
}

ProductDeliveryManagement/ProductDeliveryManagement/Views/DeliveryPersons/Edit.cshtml
@model ProductDeliveryManagement.Models.DeliveryPerson
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        <h3>Update Delivery Person</h3>
        <div class="alert alert-warning alert-dismissible fade show" role="alert" id="alert" style="display:none">
            <strong id="result">Success!</strong> <span id="msg"></span>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        @using (Html.BeginForm("Edit", "DeliveryPersons", FormMethod.Post, new { id = "frm" }))
        {
            @Html.HiddenFor(x => x.DeliveryPersonId)
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Name, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Phone, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Phone, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Address, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row mb-1">
                <div class="col-4 offset-2">
                    <button type="button" id="save" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
    <div class="col-12">
        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        $(() => {
            $("#save").click(() => {
                var valid = $("#frm").valid();
                if (valid) {
                    let data = {
                        DeliveryPersonId: $("#DeliveryPersonId").val(),
                        Name: $("#Name").val(),
                        Phone: $("#Phone").val(),
                        Address: $("#Address").val()
                    };
                    //console.log(data);
                    $.ajax({
                        type: "POST",
                        url: "/DeliveryPersons/Edit",
                        dataType: "json",
                        data: { person: data },
                        success: r => {
                            $("#msg").html(r.message);
                            $("#alert").removeClass("alert-warning")
                                .addClass("alert-success")
                                .show();
                            $("#frm").trigger('reset');
                        }
                    })
                }
            })
        });
    </script>
}

ProductDeliveryManagement/ProductDeliveryManagement/Views/DeliveryPersons/Index.cshtml
@model IEnumerable<ProductDeliveryManagement.Models.DeliveryPerson>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h3>Delivery Persons</h3>
        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Create", "Create", "DeliveryPersons", new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Delivery Person Name</th>
                    <th>Phone</th>
                    <th>Address</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var d in Model)
                {
                    <tr id="tr_@d.DeliveryPersonId">
                        <td>@d.Name</td>
                        <td>@d.Phone</td>
                        <td>@d.Address</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "DeliveryPersons", new { id = d.DeliveryPersonId }, new { @class = "btn btn-secondary btn-sm" })
                            <button type="button" data-pk="@d.DeliveryPersonId" class="btn btn-danger btn-sm del">Delete</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="d-flex justify-content-end">
            <ul class="pagination pagination-sm">
                <li class="page-item">@Html.ActionLink("First", "Index", "DeliveryPersons", new { page = 1 }, new { @class = "page-link" })</li>
                @for (var i = 1; i <= ViewBag.TotalPages; i++)
                {

                    if (ViewBag.Current == i)
                    {
                        <li class="page-item active">@Html.ActionLink(i.ToString(), "Index", "DeliveryPersons", new { page = i }, new { @class = "page-link" })</li>
                    }
                    else
                    {
                        <li class="page-item">@Html.ActionLink(i.ToString(), "Index", "DeliveryPersons", new { page = i }, new { @class = "page-link" })</li>
                    }
                }
                <li class="page-item">@Html.ActionLink("Last", "Index", "DeliveryPersons", new { page = ViewBag.TotalPages }, new { @class = "page-link" })</li>
            </ul>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        $(".del").click(function () {
            var id = $(this).data('pk');
            //console.log(id);
            if (confirm("Are you sure to Delete?")) {
                $.ajax({
                    type: "POST",
                    url: "/DeliveryPersons/Delete/" + id,
                    dataType: "json",
                    success: r => {
                        console.log(r);
                        if (r.success) {
                            $("#tr_" + id).remove();
                        }
                    }
                })
            }
        })
    </script>
}