ProductDeliveryManagement/ProductDeliveryManagement/Controllers/CrystalReportController.cs
using CrystalDecisions.CrystalReports.Engine;
using ProductDeliveryManagement.Models;
using ProductDeliveryManagement.ViewModel.Reports;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductDeliveryManagement.Controllers
{
    public class CrystalReportController : Controller
    {
        DeliveryManagementDbContext db = new DeliveryManagementDbContext();
        // GET: CrystalReport
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductReport()
        {
            var data = db.Orders.Include(o => o.Product).Select(x => new ProductReportViewModel
            {
                OrderId = x.OrderId,
                OrderDate = x.OrderDate,
                CustomerName = x.CustomerName,
                CustomerPhone = x.CustomerPhone,
                CustomerAddress = x.CustomerAddress,
                ProductId = x.ProductId,
                Quantity = x.Quantity,
                ProductName = x.Product.ProductName,
                UnitPrice = x.Product.UnitPrice
            }).ToList();
            return View(data);
        }
        public ActionResult ProductPDF()
        {
            var data = db.Orders.Include(o => o.Product).Select(x => new ProductReportViewModel
            {
                OrderId = x.OrderId,
                OrderDate = x.OrderDate,
                CustomerName = x.CustomerName,
                CustomerPhone = x.CustomerPhone,
                CustomerAddress = x.CustomerAddress,
                ProductId = x.ProductId,
                Quantity = x.Quantity,
                ProductName = x.Product.ProductName,
                UnitPrice = x.Product.UnitPrice
            }).ToList();

            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reports"), "CrystalReport2.rpt"));
            rd.SetDataSource(data);
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();

            //rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            //rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            //rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA4;

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);

            return File(stream, "application/pdf", "Products.pdf");

        }
        public ActionResult ProductExcel()
        {
            var data = db.Orders.Include(o => o.Product).Select(x => new ProductReportViewModel
            {
                OrderId = x.OrderId,
                OrderDate = x.OrderDate,
                CustomerName = x.CustomerName,
                CustomerPhone = x.CustomerPhone,
                CustomerAddress = x.CustomerAddress,
                ProductId = x.ProductId,
                Quantity = x.Quantity,
                ProductName = x.Product.ProductName,
                UnitPrice = x.Product.UnitPrice
            }).ToList();

            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reports"), "CrystalReport2.rpt"));
            rd.SetDataSource(data);
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();

            //rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            //rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            //rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA4;

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.Excel);
            stream.Seek(0, SeekOrigin.Begin);

            return File(stream, "application/vnd.ms-excel", "Products.xls");

        }
        public ActionResult DeliveryReport()
        {
            var data = db.OrdersDeliveries.Include(o => o.Order).Select(x => new DeliveryReportViewModel
            {
                OrderDeliveryId = x.OrderDeliveryId,
                DeliveryPersonId = x.DeliveryPersonId,
                DeliveryDateTime = x.DeliveryDateTime,
                IsDelivered =   x.IsDelivered,
                Name = x.DeliveryPerson.Name,
                OrderDate = x.Order.OrderDate,
                CustomerName = x.Order.CustomerName
            }).ToList();
            return View(data);
        }
        public ActionResult DeliveryPDF()
        {
            var data = db.OrdersDeliveries.Include(o => o.Order).Select(x => new DeliveryReportViewModel
            {
                OrderDeliveryId = x.OrderDeliveryId,
                DeliveryPersonId = x.DeliveryPersonId,
                DeliveryDateTime = x.DeliveryDateTime,
                IsDelivered = x.IsDelivered,
                Name = x.DeliveryPerson.Name,
                OrderDate = x.Order.OrderDate,
                CustomerName = x.Order.CustomerName
            }).ToList();

            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reports"), "CrystalReport1.rpt"));
            rd.SetDataSource(data);
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();

            //rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            //rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            //rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA4;

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);

            return File(stream, "application/pdf", "Deliveries.pdf");

        }
        public ActionResult DeliveryExcel()
        {
            var data = db.OrdersDeliveries.Include(o => o.Order).Select(x => new DeliveryReportViewModel
            {
                OrderDeliveryId = x.OrderDeliveryId,
                DeliveryPersonId = x.DeliveryPersonId,
                DeliveryDateTime = x.DeliveryDateTime,
                IsDelivered = x.IsDelivered,
                Name = x.DeliveryPerson.Name,
                OrderDate = x.Order.OrderDate,
                CustomerName = x.Order.CustomerName
            }).ToList();

            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reports"), "CrystalReport1.rpt"));
            rd.SetDataSource(data);
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();

            //rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            //rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            //rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA4;

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.Excel);
            stream.Seek(0, SeekOrigin.Begin);

            return File(stream, "application/vnd.ms-excel", "Deliveries.xls");

        }
    }
}

ProductDeliveryManagement/ProductDeliveryManagement/Controllers/OrderDeliveriesController.cs
using ProductDeliveryManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductDeliveryManagement.Controllers
{
    [Authorize]
    public class OrderDeliveriesController : Controller
    {
        DeliveryManagementDbContext db = new DeliveryManagementDbContext();
        // GET: OrderDeliveries
        public ActionResult Index(int page = 1)
        {
            int totalPages = (int)Math.Ceiling((double)db.OrdersDeliveries.Count() / 5);
            ViewBag.TotalPages = totalPages;
            ViewBag.Current = page;
            var data = db.OrdersDeliveries.OrderBy(x => x.OrderDeliveryId).Skip((page - 1) * 5).Take(5).ToList();
            return View(data);
        }
        public ActionResult Edit(int id)
        {
            return View(db.OrdersDeliveries.FirstOrDefault(x => x.OrderDeliveryId == id));
        }
        [HttpPost]
        public ActionResult Edit(OrderDelivery delivery)
        {
            if (ModelState.IsValid)
            {
                delivery.IsDelivered = true;
                db.Entry(delivery).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(delivery);
        }
    }
}

ProductDeliveryManagement/ProductDeliveryManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <style>
        body {
            padding-top: 70px;
        }
        .main {
            min-height: calc(100vh - 130px);
        }
    </style>
    @RenderSection("styles", false)
</head>
<body>
    <nav class="navbar bg-info navbar-expand-md fixed-top shadow-sm border-bottom">
        <div class="container">
            <span class="navbar-brand">Delivery Management System</span>
            <div class="navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "nav-link" })</li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">@Html.ActionLink("Products", "Index", "Products", new { }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("DeliveryPersons", "Index", "DeliveryPersons", new { }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Orders", "Index", "Orders", new { }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Order Deliverires", "Index", "OrderDeliveries", new { }, new { @class = "nav-link" })</li>
                    <li>
                        <a href="@Url.Action("ProductReport", "CrystalReport")" class="nav-link">Product Report</a>
                    </li>
                    @*<li>
                        <a href="@Url.Action("DeliveryReport", "CrystalReport")" class="nav-link">Delivery Report</a>
                    </li>*@
                </ul>
                <ul class="navbar-nav ms-auto">
                    @if (Request.IsAuthenticated)
                    {
                        <li class="nav-item">@Html.ActionLink("Logout", "Logout", "Account", new { }, new { @class = "nav-link" })</li>
                    }
                    else
                    {
                        <li class="nav-item">@Html.ActionLink("Register", "Register", "Account", new { }, new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("Login", "Login", "Account", new { }, new { @class = "nav-link" })</li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <main class="container main">
        @RenderBody()
    </main>
    <hr/>
    <footer class="container text-center bg-info">
        <p>&copy; @DateTime.Now.Year - Md.Iquball Hossain (Polock Group - One Touch Limited)</p>
    </footer>
    @RenderSection("scripts", false)
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>